import { parseQueryTags, type QueryHistoryPage, type QueryHistoryRow } from './warehouse-cancellation';
import type { QueryHistoryCoverage, QueryHistoryCoverageReason } from '../../shared/ops-contract';
import { isPlayerInsightsAgentQueryTag } from './sql-query-tags';

const QUERY_HISTORY_PAGE_SIZE = 999;
export const MAX_QUERY_HISTORY_PAGES = 40;
const MAX_QUERY_HISTORY_RANGE_MS = 30 * 24 * 60 * 60 * 1_000;
export const MAX_QUERY_HISTORY_TOTAL_RANGE_MS = 366 * 24 * 60 * 60 * 1_000;
export const QUERY_HISTORY_DEADLINE_MS = 20_000;

export interface WarehouseQueryAttribution {
  /** True only when every page and every execution-time denominator was available. */
  complete: boolean;
  /** Player Insights Agent-tagged statements not generated by a Genie space. */
  astrolabeQueries: number;
  totalQueries: number;
  astrolabeExecutionMs: number;
  totalExecutionMs: number;
  /** Ask-tagged execution attributed to one authoritative completed run. */
  askRuns?: Array<{ runId: string; executionMs: number }>;
  /** Generated SQL measured for each exact Query History Genie space id. */
  genieSpaces: Array<{ spaceId: string; queries: number; executionMs: number }>;
  /**
   * Internal user-level execution evidence.
   *
   * Populated only when Query History names the same human for both the actor
   * and the privilege identity. Service-principal and ambiguous rows never
   * enter this list.
   */
  users?: Array<{
    email: string;
    astrolabeExecutionMs: number;
    askExecutionMs?: number;
    genieSpaces: Array<{ spaceId: string; executionMs: number }>;
  }>;
  /** Present on every new read; optional only for legacy injected fixtures. */
  coverage?: QueryHistoryCoverage;
}

export const EMPTY_WAREHOUSE_QUERY_ATTRIBUTION: WarehouseQueryAttribution = {
  complete: false,
  astrolabeQueries: 0,
  totalQueries: 0,
  astrolabeExecutionMs: 0,
  totalExecutionMs: 0,
  askRuns: [],
  genieSpaces: [],
  users: [],
  coverage: {
    state: 'unavailable',
    requestedRange: null,
    queriedRange: null,
    rowsRead: 0,
    pagesRead: 0,
    chunksRead: 0,
    reasons: ['invalid-range'],
  },
};

export interface WarehouseQueryHistoryTransport {
  listQueries(input: {
    warehouseId: string;
    startTimeMs: number;
    endTimeMs: number;
    pageToken?: string;
    maxResults: number;
    signal?: AbortSignal;
  }): Promise<QueryHistoryPage>;
}

function finiteMilliseconds(value: unknown): number | null {
  const parsed = typeof value === 'number' ? value : typeof value === 'string' ? Number(value) : Number.NaN;
  return Number.isFinite(parsed) && parsed >= 0 ? parsed : null;
}

function executionMilliseconds(row: QueryHistoryRow): number | null {
  if (row.metrics && typeof row.metrics === 'object') {
    const executionTime = finiteMilliseconds((row.metrics as Record<string, unknown>).execution_time_ms);
    if (executionTime !== null) return executionTime;
  }
  return finiteMilliseconds(row.duration);
}

function rowId(row: QueryHistoryRow): string {
  return typeof row.query_id === 'string' ? row.query_id.trim() : '';
}

function interactiveRunId(row: QueryHistoryRow, runIds: ReadonlyMap<string, string>): string {
  const tags = parseQueryTags(row.query_tags);
  if (!isPlayerInsightsAgentQueryTag(tags.get('application')) || tags.get('surface') !== 'ask') return '';
  for (const key of ['run_id', 'correlation_id']) {
    const candidate = tags.get(key) ?? '';
    const runId = runIds.get(candidate);
    if (runId) return runId;
  }
  return '';
}

function isAppOperation(row: QueryHistoryRow): boolean {
  const tags = parseQueryTags(row.query_tags);
  return isPlayerInsightsAgentQueryTag(tags.get('application'));
}

function genieSpaceId(row: QueryHistoryRow): string {
  if (!row.query_source || typeof row.query_source !== 'object') return '';
  const value = (row.query_source as Record<string, unknown>).genie_space_id;
  return typeof value === 'string' ? value.trim() : '';
}

function attributableUser(row: QueryHistoryRow): string {
  const executedBy = typeof row.user_name === 'string' ? row.user_name.trim().toLowerCase() : '';
  const executedAs =
    typeof row.executed_as_user_name === 'string' ? row.executed_as_user_name.trim().toLowerCase() : '';
  if (!executedBy.includes('@') || executedBy !== executedAs) return '';
  return executedBy;
}

class QueryHistoryDeadlineError extends Error {
  constructor() {
    super('Query History read deadline reached.');
    this.name = 'QueryHistoryDeadlineError';
  }
}

function isoTimestamp(value: number): string | null {
  if (!Number.isFinite(value) || Math.abs(value) > 8_640_000_000_000_000) return null;
  return new Date(value).toISOString();
}

function addReason(coverage: QueryHistoryCoverage, reason: QueryHistoryCoverageReason): void {
  if (!coverage.reasons.includes(reason)) coverage.reasons.push(reason);
}

function abortReason(signal: AbortSignal): Error {
  return signal.reason instanceof Error ? signal.reason : new Error('Query History read aborted.');
}

function abortable<T>(work: Promise<T>, signal: AbortSignal): Promise<T> {
  if (signal.aborted) return Promise.reject(abortReason(signal));
  return new Promise<T>((resolve, reject) => {
    const onAbort = () => {
      signal.removeEventListener('abort', onAbort);
      reject(abortReason(signal));
    };
    signal.addEventListener('abort', onAbort, { once: true });
    work.then(
      (value) => {
        signal.removeEventListener('abort', onAbort);
        resolve(value);
      },
      (error) => {
        signal.removeEventListener('abort', onAbort);
        reject(error instanceof Error ? error : new Error(String(error)));
      }
    );
  });
}

/**
 * Read the complete Query History denominator for one warehouse and bounded range.
 *
 * The result contains counts and durations plus normalized human identity only
 * where actor and privilege identity agree. Query text is never copied. The
 * identity list is consumed only by the admin-guarded spend contract.
 */
export async function readWarehouseQueryAttribution(input: {
  warehouseId: string;
  startTimeMs: number;
  endTimeMs: number;
  transport: WarehouseQueryHistoryTransport;
  signal?: AbortSignal;
  /** Test seam. Callers cannot increase the production page or time budget. */
  maxPages?: number;
  deadlineMs?: number;
  now?: () => number;
  /**
   * The completed interactive Ask population from the run ledger.
   * Query tags outside this closed identifier set are never widened into Ask.
   */
  interactiveRuns?: readonly {
    runId: string;
    requestId?: string;
    correlationId: string;
    evidenceComplete?: boolean;
  }[];
}): Promise<WarehouseQueryAttribution & { coverage: QueryHistoryCoverage }> {
  const warehouseId = input.warehouseId.trim();
  const requestedFrom = isoTimestamp(input.startTimeMs);
  const requestedTo = isoTimestamp(input.endTimeMs);
  if (!warehouseId || !requestedFrom || !requestedTo || input.endTimeMs < input.startTimeMs) {
    return { ...EMPTY_WAREHOUSE_QUERY_ATTRIBUTION, coverage: EMPTY_WAREHOUSE_QUERY_ATTRIBUTION.coverage! };
  }

  const coverage: QueryHistoryCoverage = {
    state: 'partial',
    requestedRange: { from: requestedFrom, to: requestedTo },
    queriedRange: null,
    rowsRead: 0,
    pagesRead: 0,
    chunksRead: 0,
    reasons: [],
  };
  const now = input.now?.() ?? Date.now();
  const boundedEnd = Math.min(input.endTimeMs, now);
  const boundedStart = Math.max(input.startTimeMs, boundedEnd - MAX_QUERY_HISTORY_TOTAL_RANGE_MS + 1);
  if (boundedEnd !== input.endTimeMs || boundedStart !== input.startTimeMs) addReason(coverage, 'range-clamped');
  const boundedFrom = isoTimestamp(boundedStart);
  const boundedTo = isoTimestamp(boundedEnd);
  if (!boundedFrom || !boundedTo || boundedEnd < boundedStart) {
    coverage.state = 'unavailable';
    addReason(coverage, 'invalid-range');
    return { ...EMPTY_WAREHOUSE_QUERY_ATTRIBUTION, coverage };
  }

  const maximumPages = Math.max(
    1,
    Math.min(MAX_QUERY_HISTORY_PAGES, Math.floor(input.maxPages ?? MAX_QUERY_HISTORY_PAGES))
  );
  const deadlineMs = Math.max(1, Math.min(QUERY_HISTORY_DEADLINE_MS, input.deadlineMs ?? QUERY_HISTORY_DEADLINE_MS));
  const controller = new AbortController();
  const parentAbort = () => controller.abort(input.signal?.reason);
  if (input.signal?.aborted) parentAbort();
  else input.signal?.addEventListener('abort', parentAbort, { once: true });
  const timer = setTimeout(() => controller.abort(new QueryHistoryDeadlineError()), deadlineMs);
  timer.unref?.();

  const seenQueryIds = new Set<string>();
  let astrolabeQueries = 0;
  let astrolabeExecutionMs = 0;
  let totalExecutionMs = 0;
  const genieSpaces = new Map<string, { queries: number; executionMs: number }>();
  const askRuns = new Map<string, number>();
  const users = new Map<
    string,
    { astrolabeExecutionMs: number; askExecutionMs: number; genieSpaces: Map<string, number> }
  >();
  const runIds = new Map<string, string>();
  if (input.interactiveRuns?.some((run) => run.evidenceComplete === false)) {
    addReason(coverage, 'interactive-run-coverage');
  }
  for (const run of input.interactiveRuns ?? []) {
    for (const id of [run.runId, run.requestId ?? '', run.correlationId]) {
      if (id) runIds.set(id, run.runId);
    }
  }
  let totalQueries = 0;
  const aggregate = (row: QueryHistoryRow): void => {
    if (row.warehouse_id !== undefined && row.warehouse_id !== warehouseId) {
      addReason(coverage, 'unexpected-warehouse');
      return;
    }
    const id = rowId(row);
    if (!id) {
      addReason(coverage, 'invalid-row');
      return;
    }
    if (seenQueryIds.has(id)) return;
    seenQueryIds.add(id);
    totalQueries += 1;
    const spaceId = genieSpaceId(row);
    // A generated statement belongs to its exact Genie space. Excluding it from
    // the Astrolabe bucket makes the two allocations mutually exclusive.
    const interactiveRun = !spaceId ? interactiveRunId(row, runIds) : '';
    const astrolabe = !spaceId && isAppOperation(row);
    if (astrolabe) astrolabeQueries += 1;
    if (spaceId) {
      const current = genieSpaces.get(spaceId) ?? { queries: 0, executionMs: 0 };
      current.queries += 1;
      genieSpaces.set(spaceId, current);
    }
    const duration = executionMilliseconds(row);
    if (duration === null) {
      addReason(coverage, 'missing-execution-time');
      return;
    }
    totalExecutionMs += duration;
    if (astrolabe) astrolabeExecutionMs += duration;
    if (interactiveRun) askRuns.set(interactiveRun, (askRuns.get(interactiveRun) ?? 0) + duration);
    if (spaceId) genieSpaces.get(spaceId)!.executionMs += duration;
    const user = attributableUser(row);
    if (user) {
      const current = users.get(user) ?? {
        astrolabeExecutionMs: 0,
        askExecutionMs: 0,
        genieSpaces: new Map<string, number>(),
      };
      if (astrolabe) current.astrolabeExecutionMs += duration;
      if (interactiveRun) current.askExecutionMs += duration;
      if (spaceId) current.genieSpaces.set(spaceId, (current.genieSpaces.get(spaceId) ?? 0) + duration);
      users.set(user, current);
    }
  };

  let stop = controller.signal.aborted;
  try {
    for (let windowStart = boundedStart; windowStart <= boundedEnd && !stop; ) {
      if (coverage.pagesRead >= maximumPages) {
        addReason(coverage, 'page-cap');
        break;
      }
      const windowEnd = Math.min(boundedEnd, windowStart + MAX_QUERY_HISTORY_RANGE_MS - 1);
      let pageToken: string | undefined;
      const usedTokens = new Set<string>();
      coverage.chunksRead += 1;
      coverage.queriedRange = {
        from: coverage.queriedRange?.from ?? new Date(windowStart).toISOString(),
        to: new Date(windowEnd).toISOString(),
      };

      for (;;) {
        if (controller.signal.aborted) {
          stop = true;
          break;
        }
        if (coverage.pagesRead >= maximumPages) {
          addReason(coverage, 'page-cap');
          stop = true;
          break;
        }
        let response: QueryHistoryPage;
        try {
          response = await abortable(
            input.transport.listQueries({
              warehouseId,
              startTimeMs: windowStart,
              endTimeMs: windowEnd,
              pageToken,
              maxResults: QUERY_HISTORY_PAGE_SIZE,
              signal: controller.signal,
            }),
            controller.signal
          );
        } catch {
          if (controller.signal.aborted) {
            addReason(
              coverage,
              controller.signal.reason instanceof QueryHistoryDeadlineError ? 'deadline' : 'caller-abort'
            );
          } else {
            addReason(coverage, 'transport-error');
          }
          stop = true;
          break;
        }
        coverage.pagesRead += 1;
        const pageRows = Array.isArray(response.res) ? response.res : [];
        coverage.rowsRead += pageRows.length;
        for (const row of pageRows) aggregate(row);

        const next = typeof response.next_page_token === 'string' ? response.next_page_token.trim() : '';
        if (!next) {
          if (response.has_next_page) {
            addReason(coverage, 'missing-page-token');
            stop = true;
          }
          break;
        }
        if (usedTokens.has(next)) {
          addReason(coverage, 'repeated-page-token');
          stop = true;
          break;
        }
        usedTokens.add(next);
        pageToken = next;
        if (coverage.pagesRead >= maximumPages) {
          addReason(coverage, 'page-cap');
          stop = true;
          break;
        }
      }

      if (windowEnd >= boundedEnd || stop) break;
      windowStart = windowEnd + 1;
    }
  } finally {
    clearTimeout(timer);
    input.signal?.removeEventListener('abort', parentAbort);
  }

  if (controller.signal.aborted && coverage.reasons.length === 0) {
    addReason(coverage, controller.signal.reason instanceof QueryHistoryDeadlineError ? 'deadline' : 'caller-abort');
  }
  coverage.state = coverage.reasons.length === 0 ? 'complete' : 'partial';

  return {
    complete: coverage.state === 'complete',
    astrolabeQueries,
    totalQueries,
    astrolabeExecutionMs,
    totalExecutionMs,
    askRuns: [...askRuns]
      .sort(([left], [right]) => left.localeCompare(right))
      .map(([runId, executionMs]) => ({ runId, executionMs })),
    genieSpaces: [...genieSpaces].map(([spaceId, values]) => ({ spaceId, ...values })),
    users: [...users]
      .sort(([left], [right]) => left.localeCompare(right))
      .map(([email, values]) => ({
        email,
        astrolabeExecutionMs: values.astrolabeExecutionMs,
        askExecutionMs: values.askExecutionMs,
        genieSpaces: [...values.genieSpaces]
          .sort(([left], [right]) => left.localeCompare(right))
          .map(([spaceId, executionMs]) => ({ spaceId, executionMs })),
      })),
    coverage,
  };
}

interface LowLevelApiRequest {
  path: string;
  method: 'GET';
  headers: Headers;
  raw: false;
  query: {
    filter_by: {
      warehouse_ids: string[];
      query_start_time_range: { start_time_ms: number; end_time_ms: number };
    };
    include_metrics: true;
    max_results: number;
    page_token?: string;
  };
  signal?: AbortSignal;
}

export interface DatabricksLowLevelQueryHistoryClient {
  request(options: LowLevelApiRequest): Promise<unknown>;
}

function queryHistoryPage(value: unknown): QueryHistoryPage {
  if (!value || typeof value !== 'object') return {};
  const record = value as Record<string, unknown>;
  return {
    res: Array.isArray(record.res) ? (record.res as QueryHistoryRow[]) : [],
    ...(typeof record.next_page_token === 'string' ? { next_page_token: record.next_page_token } : {}),
    ...(typeof record.has_next_page === 'boolean' ? { has_next_page: record.has_next_page } : {}),
  };
}

/** Adapt the same low-level Workspace SDK pattern used by warehouse cancellation. */
export function createDatabricksQueryHistoryTransport(
  client: DatabricksLowLevelQueryHistoryClient
): WarehouseQueryHistoryTransport {
  return {
    async listQueries({ warehouseId, startTimeMs, endTimeMs, pageToken, maxResults, signal }) {
      const response = await client.request({
        path: '/api/2.0/sql/history/queries',
        method: 'GET',
        headers: new Headers({ Accept: 'application/json' }),
        raw: false,
        query: {
          filter_by: {
            warehouse_ids: [warehouseId],
            query_start_time_range: { start_time_ms: startTimeMs, end_time_ms: endTimeMs },
          },
          include_metrics: true,
          max_results: maxResults,
          ...(pageToken ? { page_token: pageToken } : {}),
        },
        signal,
      });
      return queryHistoryPage(response);
    },
  };
}

export async function createWorkspaceQueryHistoryTransport(input: {
  host: string;
  token: string;
}): Promise<WarehouseQueryHistoryTransport> {
  const { WorkspaceClient } = await import('@databricks/sdk-experimental');
  const client = new WorkspaceClient({
    host: input.host,
    token: input.token,
    authType: 'pat',
  });
  return createDatabricksQueryHistoryTransport({
    // The experimental SDK runtime forwards AbortSignal although its public
    // low-level request type has not declared the field yet.
    request: (options) => client.apiClient.request(options as never),
  });
}
