import { readFileSync } from 'node:fs';
import path from 'node:path';
import { describe, expect, it } from 'vitest';
// @ts-expect-error -- a build script, deliberately outside the tsconfig projects.
import { envNames, renderDeployAppYaml } from './deploy-app-yaml.mjs';

const repoRoot = path.resolve(__dirname, '..');
const authored = readFileSync(path.join(repoRoot, 'app.yaml'), 'utf8');

/** The deviations bundle-server.mjs applies. Kept here so the tests exercise the real shape. */
const DEPLOY_OVERRIDES = {
  banner: '# Generated by scripts/bundle-server.mjs from app.yaml. Edit that file, not this one.',
  command: "['node', 'server.mjs']",
  env: [{ name: 'NODE_ENV', value: 'production' }],
};

/**
 * The regression this file exists for.
 *
 * `PLAYER_INSIGHTS_EXPERIMENT_ID` was added to the authored app.yaml to make the
 * Run Explorer's MLflow trace deep link work, but the deployed app.yaml was
 * generated from a literal listing three other variables, so the deployed app
 * never saw it. Nothing failed: the link was simply absent in production.
 *
 * Reading the authored file from disk rather than a fixture is the point. A
 * fixture would let the two drift apart again, which is the whole defect.
 */
describe('every authored variable reaches the deploy target', () => {
  it('declares each one in the generated app.yaml', () => {
    const generated = renderDeployAppYaml(authored, DEPLOY_OVERRIDES);

    expect(envNames(authored).length).toBeGreaterThan(0);
    for (const name of envNames(authored)) {
      expect(generated,
        `${name} is declared in app.yaml but missing from the generated deploy app.yaml. ` +
          'The deployed app will not receive it, and nothing else will report that.'
      ).toContain(`name: ${name}`);
    }
  });

  it('does not carry a workspace-specific experiment id in the authored file', () => {
    const authoredId = /- name: PLAYER_INSIGHTS_EXPERIMENT_ID\n\s+value: '?(\d+)'?/.exec(authored);

    expect(authoredId,
      'app.yaml names a literal MLflow experiment id. That id belongs to one workspace and ' +
        'ships in every build, so a customer following the Run Explorer link lands on an ' +
        'experiment that does not exist in their account. The release supplies it instead.'
    ).toBeNull();
  });

  it('takes the experiment id from the release and fills the authored blank', () => {
    const generated = renderDeployAppYaml(authored, {
      ...DEPLOY_OVERRIDES,
      env: [...DEPLOY_OVERRIDES.env, { name: 'PLAYER_INSIGHTS_EXPERIMENT_ID', value: "'424242'" }],
    });
    const experimentId = /- name: PLAYER_INSIGHTS_EXPERIMENT_ID\n\s+value: '?(\d+)'?/.exec(generated);

    expect(experimentId?.[1], 'the MLflow deep link needs the id the release resolved').toBe('424242');
  });

  it('ships the shared conversation rail switched off', () => {
    const generated = renderDeployAppYaml(authored, DEPLOY_OVERRIDES);
    const authoredValue =
      /- name: PLAYER_INSIGHTS_SHARED_CONVERSATION_RAIL\n\s+value: '?([^'\n]*)'?/.exec(generated);

    // A build that resolved no value must not be the thing that opens one
    // stakeholder's conversations to another, so the authored default is the
    // safe one and the release has to say otherwise explicitly.
    expect(authoredValue?.[1],
      'app.yaml must default the shared rail to off. Anything but "false" here means a plain ' +
        '`npm run build:deploy`, with no release to resolve the variable, ships a widened rail.'
    ).toBe('false');
  });

  it('takes the shared rail setting from the release', () => {
    const generated = renderDeployAppYaml(authored, {
      ...DEPLOY_OVERRIDES,
      env: [...DEPLOY_OVERRIDES.env, { name: 'PLAYER_INSIGHTS_SHARED_CONVERSATION_RAIL', value: "'true'" }],
    });

    expect(generated).toContain("name: PLAYER_INSIGHTS_SHARED_CONVERSATION_RAIL\n    value: 'true'");
    // Replaced in place, not declared twice. A duplicate would leave the
    // container's value depending on which entry the platform read last.
    expect(generated.match(/name: PLAYER_INSIGHTS_SHARED_CONVERSATION_RAIL/g)).toHaveLength(1);
  });

  it('carries no build stamp in the authored file', () => {
    // A literal here would ship one commit's identity into every later build,
    // which is worse than no stamp: the Connections page compares this against
    // the commit the model artifact was logged from, and a frozen value would
    // report agreement or skew that has nothing to do with either side.
    const authoredSha = /- name: PLAYER_INSIGHTS_BUILD_SHA\n\s+value: '?([0-9a-f]+)'?/.exec(authored);

    expect(authoredSha, 'app.yaml names a literal commit; bundle-server.mjs resolves it from git').toBeNull();
  });

  it('takes the build stamp from the build that produced the tree', () => {
    const generated = renderDeployAppYaml(authored, {
      ...DEPLOY_OVERRIDES,
      env: [...DEPLOY_OVERRIDES.env, { name: 'PLAYER_INSIGHTS_BUILD_SHA', value: "'abc123+dirty'" }],
    });

    expect(generated).toContain("name: PLAYER_INSIGHTS_BUILD_SHA\n    value: 'abc123+dirty'");
    expect(generated.match(/name: PLAYER_INSIGHTS_BUILD_SHA/g)).toHaveLength(1);
  });

  it('declares the judge endpoint, which the server has always read', () => {
    // The regression this whole file exists for, found a second time: the server
    // read PLAYER_INSIGHTS_JUDGE_ENDPOINT and no app.yaml ever set it, so the
    // variable was decoration and every deployment used the compiled default.
    // Empty is the correct authored value (the judge is per deployment), but
    // absent means unreachable.
    expect(envNames(authored)).toContain('PLAYER_INSIGHTS_JUDGE_ENDPOINT');

    const generated = renderDeployAppYaml(authored, {
      ...DEPLOY_OVERRIDES,
      env: [
        ...DEPLOY_OVERRIDES.env,
        { name: 'PLAYER_INSIGHTS_JUDGE_ENDPOINT', value: "'databricks-claude-opus-4'" },
      ],
    });
    expect(generated).toContain("name: PLAYER_INSIGHTS_JUDGE_ENDPOINT\n    value: 'databricks-claude-opus-4'");
  });

  it('keeps resource-backed variables bound to their resource', () => {
    const generated = renderDeployAppYaml(authored, DEPLOY_OVERRIDES);

    expect(generated).toContain('valueFrom: postgres');
    expect(generated).toContain('valueFrom: serving-endpoint');
  });

  it('preserves the comments explaining why a variable is there', () => {
    const generated = renderDeployAppYaml(authored, DEPLOY_OVERRIDES);
    const authoredComments = authored
      .split('\n')
      .map((line) => line.trim())
      .filter((line) => line.startsWith('#'));

    expect(authoredComments.length).toBeGreaterThan(0);
    for (const comment of authoredComments) {
      expect(generated, `the deploy file dropped an authored comment: ${comment}`).toContain(comment);
    }
  });
});

describe('the deploy-target deviations', () => {
  it('replaces the command, because the deploy tree has no package.json to npm-run', () => {
    const generated = renderDeployAppYaml(authored, DEPLOY_OVERRIDES);

    expect(generated).toContain("command: ['node', 'server.mjs']");
    expect(generated).not.toContain('npm');
  });

  it('adds NODE_ENV, which the replaced npm script used to set', () => {
    expect(renderDeployAppYaml(authored, DEPLOY_OVERRIDES)).toContain('value: production');
  });

  it('replaces an authored variable in place rather than declaring it twice', () => {
    const source = "command: ['npm', 'run', 'start']\nenv:\n  - name: NODE_ENV\n    value: development\n";
    const generated = renderDeployAppYaml(source, DEPLOY_OVERRIDES);

    expect(generated.match(/name: NODE_ENV/g)).toHaveLength(1);
    expect(generated).not.toContain('development');
  });

  it('names the authored file as the one to edit', () => {
    expect(renderDeployAppYaml(authored, DEPLOY_OVERRIDES).startsWith('# Generated by')).toBe(true);
  });
});

/**
 * Silence is the failure mode being designed out, so the parser refuses input it
 * does not understand instead of dropping it. If app.yaml grows a construct
 * these patterns miss, the build stops and the transform gets widened
 * deliberately.
 */
describe('unparseable config fails the build rather than vanishing', () => {
  it('rejects an env entry with no name', () => {
    expect(() => renderDeployAppYaml('env:\n  - valueFrom: postgres\n', {})).toThrow(/without a name/);
  });

  it('rejects an inline env value it would otherwise silently replace', () => {
    expect(() => renderDeployAppYaml('env: []\n', { env: [{ name: 'A', value: 'b' }] })).toThrow(/inline env/);
  });

  it('rejects an env line matching neither an entry nor a continuation', () => {
    expect(() => renderDeployAppYaml('env:\n - name: A\n', {})).toThrow(/cannot parse env line/);
  });

  it('passes through top-level keys it has no opinion about', () => {
    const generated = renderDeployAppYaml('command: []\nresources:\n  - name: postgres\n', {});

    expect(generated).toContain('resources:');
    expect(generated).toContain('- name: postgres');
  });
});

/**
 * The transform only helps while the bundler uses it. This is the same guard
 * server.test.ts applies to the serving plugin: assert against the source, so
 * reintroducing the literal fails rather than quietly restoring the old bug.
 */
describe('the bundler derives rather than reconstructs', () => {
  const bundler = readFileSync(path.join(repoRoot, 'scripts/bundle-server.mjs'), 'utf8');

  it('calls the transform, pointed at the authored file', () => {
    expect(bundler).toContain('writeDeployAppYaml');
    expect(bundler).toMatch(/from:\s*path\.join\(root, 'app\.yaml'\)/);
  });

  it('has no literal env block of its own', () => {
    const withoutComments = bundler.replace(/\/\*[\s\S]*?\*\//g, '').replace(/\/\/[^\n]*/g, '');

    expect(withoutComments,
      'bundle-server.mjs is writing app.yaml env from a literal again. That is a second source ' +
        'of truth, and it drops whatever app.yaml adds.'
    ).not.toMatch(/env:\s*\\n\s*-\s*name:|`command:[\s\S]*?\nenv:/);
  });
});
