import { existsSync, readFileSync } from 'node:fs';
import path from 'node:path';
import { describe, expect, it } from 'vitest';
// @ts-expect-error -- a build script, deliberately outside the tsconfig projects.
import { envNames, renderDeployAppYaml } from './deploy-app-yaml.mjs';
// @ts-expect-error -- a build script, deliberately outside the tsconfig projects.
import { validateRuntimePersonas } from './check-runtime-personas.mjs';

const repoRoot = path.resolve(__dirname, '..');
const authored = readFileSync(path.join(repoRoot, 'app.yaml'), 'utf8');
const bundleYaml = readFileSync(path.join(repoRoot, '..', 'databricks.yml'), 'utf8');
const bundleServer = readFileSync(path.join(repoRoot, 'scripts', 'bundle-server.mjs'), 'utf8');
const appRelease = readFileSync(path.join(repoRoot, '..', 'bundle', 'app-release.sh'), 'utf8');
const appSourceStaging = readFileSync(path.join(repoRoot, '..', 'bundle', 'app-source-staging.sh'), 'utf8');
const defaultPersonaTemplates = readFileSync(path.join(repoRoot, 'shared', 'default-sp-persona-templates.ts'), 'utf8');
const accountRoutingSources = [
  authored,
  bundleServer,
  readFileSync(path.join(repoRoot, 'shared', 'account-feedback.ts'), 'utf8'),
  readFileSync(path.join(repoRoot, 'client', 'src', 'AccountMenuPanel.tsx'), 'utf8'),
];
const idlePolicyDocuments = [
  readFileSync(path.join(repoRoot, '..', 'README.md'), 'utf8'),
  readFileSync(path.join(repoRoot, '..', 'mirror', 'public-README.md'), 'utf8'),
  readFileSync(path.join(repoRoot, '..', 'bundle', 'DECISIONS.md'), 'utf8'),
  readFileSync(path.join(repoRoot, '..', 'docs', 'Player_Insights_Agent_Access_Guide.md'), 'utf8'),
  readFileSync(path.join(repoRoot, '..', 'docs', 'Player_Insights_Agent_Security_Access_Specification.md'), 'utf8'),
  authored,
  bundleYaml,
];

/** The deviations bundle-server.mjs applies. Kept here so the tests exercise the real shape. */
const DEPLOY_OVERRIDES = {
  banner: '# Generated by scripts/bundle-server.mjs from app.yaml. Edit that file, not this one.',
  command: "['node', 'server.mjs']",
  env: [{ name: 'NODE_ENV', value: 'production' }],
};
const REQUIRED_ASK_SCOPES = ['serving.serving-endpoints', 'model-serving', 'sql', 'dashboards.genie'];
const GIT_DEPLOY_SCOPES = [...REQUIRED_ASK_SCOPES, 'workspace.workspace:read', 'postgres'];
const OPTIONAL_BROWSE_SCOPES = [
  'catalog.catalogs:read',
  'catalog.schemas:read',
  'catalog.tables:read',
  'workspace.workspace:read',
  'vectorsearch.vector-search-indexes:read',
  'vectorsearch.vector-search-endpoints:read',
  'postgres',
];

function declaredScopes(yaml: string): string[] {
  const value = /- name: PLAYER_INSIGHTS_USER_API_SCOPES\n\s+value: '?([^'\n]*)'?/.exec(yaml)?.[1] ?? '';
  return value.split(',').filter(Boolean);
}

/**
 * The regression this file exists for.
 *
 * `PLAYER_INSIGHTS_EXPERIMENT_ID` was added to the authored app.yaml to make the
 * Run Explorer's MLflow trace deep link work, but the deployed app.yaml was
 * generated from a literal listing three other variables, so the deployed app
 * never saw it. Nothing failed: the link was simply absent in production.
 *
 * Reading the authored file from disk rather than a fixture is the point. A
 * fixture would let the two drift apart again, which is the whole defect.
 */
describe('every authored variable reaches the deploy target', () => {
  it('declares each one in the generated app.yaml', () => {
    const generated = renderDeployAppYaml(authored, DEPLOY_OVERRIDES);

    expect(envNames(authored).length).toBeGreaterThan(0);
    for (const name of envNames(authored)) {
      expect(
        generated,
        `${name} is declared in app.yaml but missing from the generated deploy app.yaml. ` +
          'The deployed app will not receive it, and nothing else will report that.'
      ).toContain(`name: ${name}`);
    }
  });

  it('does not carry a workspace-specific experiment id in the authored file', () => {
    const authoredId = /- name: PLAYER_INSIGHTS_EXPERIMENT_ID\n\s+value: '?(\d+)'?/.exec(authored);

    expect(
      authoredId,
      'app.yaml names a literal MLflow experiment id. That id belongs to one workspace and ' +
        'ships in every build, so a customer following the Run Explorer link lands on an ' +
        'experiment that does not exist in their account. The release supplies it instead.'
    ).toBeNull();
  });

  it('takes the experiment id from the release and fills the authored blank', () => {
    const generated = renderDeployAppYaml(authored, {
      ...DEPLOY_OVERRIDES,
      env: [...DEPLOY_OVERRIDES.env, { name: 'PLAYER_INSIGHTS_EXPERIMENT_ID', value: "'424242'" }],
    });
    const experimentId = /- name: PLAYER_INSIGHTS_EXPERIMENT_ID\n\s+value: '?(\d+)'?/.exec(generated);

    expect(experimentId?.[1], 'the MLflow deep link needs the id the release resolved').toBe('424242');
  });

  it('takes the bundle-owned rebuild job id from the release', () => {
    const generated = renderDeployAppYaml(authored, {
      ...DEPLOY_OVERRIDES,
      env: [...DEPLOY_OVERRIDES.env, { name: 'PLAYER_INSIGHTS_INDEX_REBUILD_JOB_ID', value: "'987654'" }],
    });
    const jobId = /- name: PLAYER_INSIGHTS_INDEX_REBUILD_JOB_ID\n\s+value: '?(\d+)'?/.exec(generated);

    expect(jobId?.[1], 'Ops needs the real job id to join JOBS billing rows').toBe('987654');
  });

  it('ships every Git deploy with ask-path and workspace browse scopes', () => {
    const generated = renderDeployAppYaml(authored, DEPLOY_OVERRIDES);

    expect(
      declaredScopes(generated),
      'A plain build produces build/deploy/app.yaml, which Deploy from Git runs. Leaving this ' +
        'empty makes the login gate say Player Insights Agent needs no serving, SQL, or Genie scopes.'
    ).toEqual(GIT_DEPLOY_SCOPES);
  });

  it('keeps optional scopes other than workspace and Lakebase browse out of Git deploys', () => {
    const generated = renderDeployAppYaml(authored, DEPLOY_OVERRIDES);
    const declared = declaredScopes(generated);

    for (const optional of OPTIONAL_BROWSE_SCOPES.filter(
      (scope) => !['workspace.workspace:read', 'postgres'].includes(scope)
    )) {
      expect(declared).not.toContain(optional);
    }
  });

  it('lets a bundle release replace the Git fallback with its exact App declaration', () => {
    const resolved = [...REQUIRED_ASK_SCOPES, ...OPTIONAL_BROWSE_SCOPES].join(',');
    const generated = renderDeployAppYaml(authored, {
      ...DEPLOY_OVERRIDES,
      env: [...DEPLOY_OVERRIDES.env, { name: 'PLAYER_INSIGHTS_USER_API_SCOPES', value: `'${resolved}'` }],
    });

    expect(declaredScopes(generated)).toEqual([...REQUIRED_ASK_SCOPES, ...OPTIONAL_BROWSE_SCOPES]);
    expect(generated.match(/name: PLAYER_INSIGHTS_USER_API_SCOPES/g)).toHaveLength(1);
  });

  it('ships the shared conversation rail switched off', () => {
    const generated = renderDeployAppYaml(authored, DEPLOY_OVERRIDES);
    const authoredValue = /- name: PLAYER_INSIGHTS_SHARED_CONVERSATION_RAIL\n\s+value: '?([^'\n]*)'?/.exec(generated);

    // A build that resolved no value must not be the thing that opens one
    // stakeholder's conversations to another, so the authored default is the
    // safe one and the release has to say otherwise explicitly.
    expect(
      authoredValue?.[1],
      'app.yaml must default the shared rail to off. Anything but "false" here means a plain ' +
        '`npm run build:deploy`, with no release to resolve the variable, ships a widened rail.'
    ).toBe('false');
  });

  it('takes the shared rail setting from the release', () => {
    const generated = renderDeployAppYaml(authored, {
      ...DEPLOY_OVERRIDES,
      env: [...DEPLOY_OVERRIDES.env, { name: 'PLAYER_INSIGHTS_SHARED_CONVERSATION_RAIL', value: "'true'" }],
    });

    expect(generated).toContain("name: PLAYER_INSIGHTS_SHARED_CONVERSATION_RAIL\n    value: 'true'");
    // Replaced in place, not declared twice. A duplicate would leave the
    // container's value depending on which entry the platform read last.
    expect(generated.match(/name: PLAYER_INSIGHTS_SHARED_CONVERSATION_RAIL/g)).toHaveLength(1);
  });

  it('ships the conservative app idle timeout and lets a release override it', () => {
    const authoredTimeout = /- name: PLAYER_INSIGHTS_IDLE_TIMEOUT_MINUTES\n\s+value: '?([^'\n]*)'?/.exec(authored)?.[1];
    expect(authoredTimeout).toBe('120');
    expect(bundleYaml).toMatch(
      /app_idle_timeout_minutes:\n\s+description:[\s\S]*?Defaults to 120[\s\S]*?\n\s+default: "120"/
    );
    expect(appRelease).toContain('bundle_var_or_empty app_idle_timeout_minutes');
    expect(appRelease).toContain(
      'IDLE_TIMEOUT="${PLAYER_INSIGHTS_IDLE_TIMEOUT_MINUTES:-$(bundle_var_or_empty app_idle_timeout_minutes)}"'
    );
    expect(appRelease).toContain('PLAYER_INSIGHTS_IDLE_TIMEOUT_MINUTES="$IDLE_TIMEOUT"');
    expect(bundleServer).toContain('process.env.PLAYER_INSIGHTS_IDLE_TIMEOUT_MINUTES');

    const generated = renderDeployAppYaml(authored, {
      ...DEPLOY_OVERRIDES,
      env: [...DEPLOY_OVERRIDES.env, { name: 'PLAYER_INSIGHTS_IDLE_TIMEOUT_MINUTES', value: "'90'" }],
    });
    expect(generated).toContain("name: PLAYER_INSIGHTS_IDLE_TIMEOUT_MINUTES\n    value: '90'");
    expect(generated.match(/name: PLAYER_INSIGHTS_IDLE_TIMEOUT_MINUTES/g)).toHaveLength(1);
  });

  it('keeps every active timeout policy document on the two-hour default', () => {
    for (const document of idlePolicyDocuments) {
      expect(document).toMatch(/120[\s\S]{0,40}2 hours/);
      expect(document).not.toMatch(
        /(?:defaults? to|default is|default idle limit|idle limit defaults to)[^\n]{0,30}(?:30|45)(?:`)?(?: minutes)?/i
      );
    }
  });

  it('carries no build stamp in the authored file', () => {
    // A literal here would ship one commit's identity into every later build,
    // which is worse than no stamp: the Connections page compares this against
    // the commit the model artifact was logged from, and a frozen value would
    // report agreement or skew that has nothing to do with either side.
    const authoredSha = /- name: PLAYER_INSIGHTS_BUILD_SHA\n\s+value: '?([0-9a-f]+)'?/.exec(authored);

    expect(authoredSha, 'app.yaml names a literal commit; bundle-server.mjs resolves it from git').toBeNull();
  });

  it('takes the build stamp from the build that produced the tree', () => {
    const generated = renderDeployAppYaml(authored, {
      ...DEPLOY_OVERRIDES,
      env: [...DEPLOY_OVERRIDES.env, { name: 'PLAYER_INSIGHTS_BUILD_SHA', value: "'abc123+dirty'" }],
    });

    expect(generated).toContain("name: PLAYER_INSIGHTS_BUILD_SHA\n    value: 'abc123+dirty'");
    expect(generated.match(/name: PLAYER_INSIGHTS_BUILD_SHA/g)).toHaveLength(1);
  });

  it('declares the judge endpoint, which the server has always read', () => {
    // The regression this whole file exists for, found a second time: the server
    // read PLAYER_INSIGHTS_JUDGE_ENDPOINT and no app.yaml ever set it, so the
    // variable was decoration and every deployment used the compiled default.
    // Empty is the correct authored value (the judge is per deployment), but
    // absent means unreachable.
    expect(envNames(authored)).toContain('PLAYER_INSIGHTS_JUDGE_ENDPOINT');

    const generated = renderDeployAppYaml(authored, {
      ...DEPLOY_OVERRIDES,
      env: [...DEPLOY_OVERRIDES.env, { name: 'PLAYER_INSIGHTS_JUDGE_ENDPOINT', value: "'databricks-claude-opus-4'" }],
    });
    expect(generated).toContain("name: PLAYER_INSIGHTS_JUDGE_ENDPOINT\n    value: 'databricks-claude-opus-4'");
  });

  it('declares catalog, schema and Genie ids empty in source', () => {
    for (const name of [
      'PLAYER_INSIGHTS_CATALOG',
      'PLAYER_INSIGHTS_SCHEMA',
      'PLAYER_INSIGHTS_DATA_GENIE_ID',
      'PLAYER_INSIGHTS_DICTIONARY_GENIE_ID',
      'PLAYER_INSIGHTS_LLM_ENDPOINT',
      'PLAYER_INSIGHTS_SEMANTIC_INDEX',
      'PLAYER_INSIGHTS_SEMANTIC_ENDPOINT',
    ]) {
      expect(envNames(authored)).toContain(name);
      const authoredValue = new RegExp(`- name: ${name}\\n\\s+value: '?([^'\\n]*)'?`).exec(authored)?.[1] ?? 'MISSING';
      expect(authoredValue, `${name} must stay empty in source so a Git deploy ships no customer names`).toBe('');
    }
  });

  it('takes catalog, schema and Genie ids from the release', () => {
    const generated = renderDeployAppYaml(authored, {
      ...DEPLOY_OVERRIDES,
      env: [
        ...DEPLOY_OVERRIDES.env,
        { name: 'PLAYER_INSIGHTS_CATALOG', value: "'example_catalog'" },
        { name: 'PLAYER_INSIGHTS_SCHEMA', value: "'example_schema'" },
        { name: 'PLAYER_INSIGHTS_DATA_GENIE_ID', value: "'space-data'" },
        { name: 'PLAYER_INSIGHTS_DICTIONARY_GENIE_ID', value: "'space-dict'" },
        { name: 'PLAYER_INSIGHTS_LLM_ENDPOINT', value: "'databricks-claude-sonnet-4-6'" },
        { name: 'PLAYER_INSIGHTS_SEMANTIC_INDEX', value: "'example_catalog.example_schema.semantic_index'" },
        { name: 'PLAYER_INSIGHTS_SEMANTIC_ENDPOINT', value: "'semantic-endpoint'" },
      ],
    });
    expect(generated).toContain("name: PLAYER_INSIGHTS_CATALOG\n    value: 'example_catalog'");
    expect(generated).toContain("name: PLAYER_INSIGHTS_SCHEMA\n    value: 'example_schema'");
    expect(generated).toContain("name: PLAYER_INSIGHTS_DATA_GENIE_ID\n    value: 'space-data'");
    expect(generated).toContain("name: PLAYER_INSIGHTS_DICTIONARY_GENIE_ID\n    value: 'space-dict'");
    expect(generated).toContain("name: PLAYER_INSIGHTS_LLM_ENDPOINT\n    value: 'databricks-claude-sonnet-4-6'");
    expect(generated).toContain(
      "name: PLAYER_INSIGHTS_SEMANTIC_INDEX\n    value: 'example_catalog.example_schema.semantic_index'"
    );
    expect(generated).toContain("name: PLAYER_INSIGHTS_SEMANTIC_ENDPOINT\n    value: 'semantic-endpoint'");
    expect(generated.match(/name: PLAYER_INSIGHTS_CATALOG/g)).toHaveLength(1);
  });

  it('carries the bundle foundation model into a target release without baking it into public source', () => {
    expect(bundleServer).toContain('process.env.PLAYER_INSIGHTS_LLM_ENDPOINT');
    expect(bundleServer).toContain("name: 'PLAYER_INSIGHTS_LLM_ENDPOINT'");
    expect(appRelease).toContain('LLM_ENDPOINT="$(bundle_var llm_direct_endpoint)"');
    expect(appRelease).toContain('PLAYER_INSIGHTS_LLM_ENDPOINT="$LLM_ENDPOINT"');
  });

  it('carries both active Vector Search identities and rejects a one-sided release', () => {
    expect(bundleServer).toContain('process.env.PLAYER_INSIGHTS_SEMANTIC_INDEX');
    expect(bundleServer).toContain('process.env.PLAYER_INSIGHTS_SEMANTIC_ENDPOINT');
    expect(appRelease).toContain('SEMANTIC_INDEX_NAME="$(bundle_var_or_empty semantic_index_name)"');
    expect(appRelease).toContain('PLAYER_INSIGHTS_SEMANTIC_INDEX="$SEMANTIC_INDEX_NAME"');
    expect(appRelease).toContain('PLAYER_INSIGHTS_SEMANTIC_ENDPOINT="$SEMANTIC_INDEX_ENDPOINT"');
    expect(appRelease).toContain('semantic_index_endpoint is set but semantic_index_name is empty');
    expect(appRelease).toContain('vector-search-indexes get-index "$SEMANTIC_INDEX_NAME"');
    expect(appRelease).toContain('semantic_index_endpoint does not match the active index host');
    expect(appRelease).toContain('vector-search-endpoints get-endpoint "$LIVE_SEMANTIC_ENDPOINT"');
    expect(appRelease.indexOf('vector-search-indexes get-index')).toBeLessThan(
      appRelease.indexOf('clean_and_import_app_source "$DEPLOY_TREE"')
    );
    expect(appSourceStaging).toContain(
      'databricks workspace import-dir "$source_dir" "$source_path" --overwrite --profile "$profile"'
    );
  });

  it('carries no administrator address in the authored file', () => {
    // Every other variable here is a resource. This one is people, and both
    // halves of an address -- the personal name and the employer -- are on the
    // publication's sensitive list. A literal would ship one workspace's
    // employees into every build of a repo customers deploy from.
    const authoredList = /- name: PLAYER_INSIGHTS_ADMIN_EMAILS\n\s+value: '?([^'\n]*)'?/.exec(authored);

    expect(
      authoredList?.[1],
      'app.yaml names a literal administrator. The list belongs in the git-ignored ' +
        '.databricks/bundle/<target>/variable-overrides.json, and the release supplies it.'
    ).toBe('');
  });

  it('takes the administrator list from the release', () => {
    const generated = renderDeployAppYaml(authored, {
      ...DEPLOY_OVERRIDES,
      env: [...DEPLOY_OVERRIDES.env, { name: 'PLAYER_INSIGHTS_ADMIN_EMAILS', value: "'someone@example.com'" }],
    });

    expect(generated).toContain("name: PLAYER_INSIGHTS_ADMIN_EMAILS\n    value: 'someone@example.com'");
    expect(generated.match(/name: PLAYER_INSIGHTS_ADMIN_EMAILS/g)).toHaveLength(1);
  });

  it('keeps account routing deployment-only and carries explicit release values without swapping routes', () => {
    for (const name of [
      'PLAYER_INSIGHTS_FEEDBACK_SLACK_URL',
      'PLAYER_INSIGHTS_FEEDBACK_SLACK_LABEL',
      'PLAYER_INSIGHTS_ESCALATION_SLACK_URL',
      'PLAYER_INSIGHTS_ESCALATION_SLACK_LABEL',
    ]) {
      const localName = name.replace('PLAYER_INSIGHTS_', '');
      expect(envNames(authored)).toContain(name);
      expect(new RegExp(`- name: ${name}\\n\\s+value: '?([^'\\n]*)'?`).exec(authored)?.[1]).toBe('');
      expect(bundleServer).toContain(`process.env.${name}`);
      expect(appRelease).toContain(`${localName}="\${${name}:-}"`);
      expect(appRelease).toContain(`${name}="$${localName}"`);
    }

    const feedbackUrl = `slack://user?team=T${'1'.repeat(8)}&id=U${'2'.repeat(8)}`;
    const escalationUrl = `https://app.slack.com/client/T${'3'.repeat(8)}/search?q=Customer%20Admin`;
    const generated = renderDeployAppYaml(authored, {
      ...DEPLOY_OVERRIDES,
      env: [
        ...DEPLOY_OVERRIDES.env,
        { name: 'PLAYER_INSIGHTS_FEEDBACK_SLACK_URL', value: `'${feedbackUrl}'` },
        { name: 'PLAYER_INSIGHTS_FEEDBACK_SLACK_LABEL', value: "'Message Maintainer in Slack'" },
        { name: 'PLAYER_INSIGHTS_ESCALATION_SLACK_URL', value: `'${escalationUrl}'` },
        { name: 'PLAYER_INSIGHTS_ESCALATION_SLACK_LABEL', value: "'Find Customer Admin in Slack'" },
      ],
    });
    expect(generated).toContain(`name: PLAYER_INSIGHTS_FEEDBACK_SLACK_URL\n    value: '${feedbackUrl}'`);
    expect(generated).toContain("name: PLAYER_INSIGHTS_FEEDBACK_SLACK_LABEL\n    value: 'Message Maintainer in Slack'");
    expect(generated).toContain(`name: PLAYER_INSIGHTS_ESCALATION_SLACK_URL\n    value: '${escalationUrl}'`);
    expect(generated).toContain(
      "name: PLAYER_INSIGHTS_ESCALATION_SLACK_LABEL\n    value: 'Find Customer Admin in Slack'"
    );
    expect(generated.indexOf(feedbackUrl)).toBeLessThan(generated.indexOf(escalationUrl));
    expect(appRelease).toContain('on_exit restore_deploy_app_yaml');
    expect(appRelease).toContain('git -C "$BUNDLE_ROOT" restore -- "$DEPLOY_APP_YAML_REL"');
  });

  it('keeps people, team ids, and member ids out of neutral build sources', () => {
    const neutralBuildSource = [...accountRoutingSources, renderDeployAppYaml(authored, DEPLOY_OVERRIDES)].join('\n');
    const privateValues = [
      ['Named', 'Maintainer'].join(' '),
      ['Customer', 'Administrator'].join(' '),
      ['T00', 'PRIVATE'].join(''),
      ['U00', 'PRIVATE'].join(''),
    ];
    for (const value of privateValues) expect(neutralBuildSource).not.toContain(value);
  });

  it('embeds public defaults in the server and carries only explicit deployment overrides in app.yaml', () => {
    expect(envNames(authored)).toContain('PLAYER_INSIGHTS_PERSONA_TEMPLATES');
    expect(/- name: PLAYER_INSIGHTS_PERSONA_TEMPLATES\n\s+value: '?([^'\n]*)'?/.exec(authored)?.[1]).toBe('');
    expect(bundleServer).toContain('process.env.PLAYER_INSIGHTS_PERSONA_TEMPLATES');
    expect(bundleServer).toContain("name: 'PLAYER_INSIGHTS_PERSONA_TEMPLATES'");
    expect(appRelease).toContain('bundle/targets/$TARGET/persona-templates.json');
    expect(appRelease).toContain('PLAYER_INSIGHTS_PERSONA_TEMPLATES="$PERSONA_TEMPLATE_OVERRIDE"');
    expect(defaultPersonaTemplates).toContain("id: 'business-analyst'");
    expect(defaultPersonaTemplates).toContain("id: 'marketing-scientist'");

    const configured = '{"mode":"extend","templates":[]}';
    const generated = renderDeployAppYaml(authored, {
      ...DEPLOY_OVERRIDES,
      env: [...DEPLOY_OVERRIDES.env, { name: 'PLAYER_INSIGHTS_PERSONA_TEMPLATES', value: `'${configured}'` }],
    });
    expect(generated).toContain(`name: PLAYER_INSIGHTS_PERSONA_TEMPLATES\n    value: '${configured}'`);
    expect(generated.match(/name: PLAYER_INSIGHTS_PERSONA_TEMPLATES/g)).toHaveLength(1);
  });

  it('keeps resource-backed variables bound to their resource', () => {
    const generated = renderDeployAppYaml(authored, DEPLOY_OVERRIDES);

    expect(generated).toContain('valueFrom: postgres');
    expect(generated).toContain('valueFrom: serving-endpoint');
  });

  it('preserves the comments explaining why a variable is there', () => {
    const generated = renderDeployAppYaml(authored, DEPLOY_OVERRIDES);
    const authoredComments = authored
      .split('\n')
      .map((line) => line.trim())
      .filter((line) => line.startsWith('#'));

    expect(authoredComments.length).toBeGreaterThan(0);
    for (const comment of authoredComments) {
      expect(generated, `the deploy file dropped an authored comment: ${comment}`).toContain(comment);
    }
  });
});

describe('the deploy-target deviations', () => {
  it('replaces the command, because the deploy tree has no package.json to npm-run', () => {
    const generated = renderDeployAppYaml(authored, DEPLOY_OVERRIDES);

    expect(generated).toContain("command: ['node', 'server.mjs']");
    expect(generated).not.toContain('npm');
  });

  it('adds NODE_ENV, which the replaced npm script used to set', () => {
    expect(renderDeployAppYaml(authored, DEPLOY_OVERRIDES)).toContain('value: production');
  });

  it('replaces an authored variable in place rather than declaring it twice', () => {
    const source = "command: ['npm', 'run', 'start']\nenv:\n  - name: NODE_ENV\n    value: development\n";
    const generated = renderDeployAppYaml(source, DEPLOY_OVERRIDES);

    expect(generated.match(/name: NODE_ENV/g)).toHaveLength(1);
    expect(generated).not.toContain('development');
  });

  it('names the authored file as the one to edit', () => {
    expect(renderDeployAppYaml(authored, DEPLOY_OVERRIDES).startsWith('# Generated by')).toBe(true);
  });
});

/**
 * Silence is the failure mode being designed out, so the parser refuses input it
 * does not understand instead of dropping it. If app.yaml grows a construct
 * these patterns miss, the build stops and the transform gets widened
 * deliberately.
 */
describe('unparseable config fails the build rather than vanishing', () => {
  it('rejects an env entry with no name', () => {
    expect(() => renderDeployAppYaml('env:\n  - valueFrom: postgres\n', {})).toThrow(/without a name/);
  });

  it('rejects an inline env value it would otherwise silently replace', () => {
    expect(() => renderDeployAppYaml('env: []\n', { env: [{ name: 'A', value: 'b' }] })).toThrow(/inline env/);
  });

  it('rejects an env line matching neither an entry nor a continuation', () => {
    expect(() => renderDeployAppYaml('env:\n - name: A\n', {})).toThrow(/cannot parse env line/);
  });

  it('passes through top-level keys it has no opinion about', () => {
    const generated = renderDeployAppYaml('command: []\nresources:\n  - name: postgres\n', {});

    expect(generated).toContain('resources:');
    expect(generated).toContain('- name: postgres');
  });
});

/**
 * build/deploy is COMMITTED, so the app can be deployed straight from Git. A
 * release resolves the administrator list into it, which makes a routine
 * `git add` after a release the whole leak: a personal name and an employer,
 * in a tracked file.
 *
 * The release does not need the commit. It uploads the local build tree with
 * `workspace import-dir`, so the container has the list either way. This test
 * is the alarm for the window in between, and failing it means the tree is not
 * committable rather than that the build is wrong.
 *
 * The directory stopped publishing, so a fresh public clone has no built tree
 * to read until its owner builds one, and reading it unconditionally would
 * fail that person's first `npm test` on a file they were never given. Here
 * the tree is tracked and is always on disk, so its ABSENCE is itself the
 * failure -- which is why the missing case still fails internally and is
 * silent only where `mirror/` is gone, i.e. in the publication.
 */
const DEPLOYED_APP_YAML = path.join(repoRoot, 'build/deploy/app.yaml');
const DEPLOYED_SERVER = path.join(repoRoot, 'build/deploy/server.mjs');
const INTERNAL_TREE = existsSync(path.join(repoRoot, '..', 'mirror', 'publish-exclude.txt'));

describe('the committed deploy tree names no administrator', () => {
  it('carries an empty administrator list, or none at all', () => {
    if (!existsSync(DEPLOYED_APP_YAML)) {
      expect(
        INTERNAL_TREE,
        'build/deploy/app.yaml is missing from the internal tree, where it is tracked and is ' +
          'the file this guard reads. Put it back with: ' +
          'git restore -- ':(glob)*/build/deploy/app.yaml''
      ).toBe(false);
      return;
    }

    const deployed = readFileSync(DEPLOYED_APP_YAML, 'utf8');
    const list = /- name: PLAYER_INSIGHTS_ADMIN_EMAILS\n\s+value: '?([^'\n]*)'?/.exec(deployed);

    expect(
      list?.[1] ?? '',
      'build/deploy/app.yaml carries administrator addresses. That file is tracked and is ' +
        'published to customers. This is what a release leaves behind and it must not be ' +
        'committed. The app was still deployed with the list, because the release uploads the ' +
        'local tree directly. Put it back with: git restore -- ':(glob)*/build/deploy/app.yaml''
    ).toBe('');
  });

  it('embeds both public default persona profiles for Deploy from Git', () => {
    if (!existsSync(DEPLOYED_SERVER)) {
      expect(
        INTERNAL_TREE,
        'build/deploy/server.mjs is missing from the internal tree, where the public Git artifact is tracked'
      ).toBe(false);
      return;
    }
    const result = validateRuntimePersonas(DEPLOYED_SERVER);
    expect(result.findings, `${result.findings.join('\n')}\nInspected: ${result.files.join(', ')}`).toEqual([]);
  });
});

/**
 * The transform only helps while the bundler uses it. This is the same guard
 * server.test.ts applies to the serving plugin: assert against the source, so
 * reintroducing the literal fails rather than quietly restoring the old bug.
 */
describe('the bundler derives rather than reconstructs', () => {
  const bundler = readFileSync(path.join(repoRoot, 'scripts/bundle-server.mjs'), 'utf8');

  it('calls the transform, pointed at the authored file', () => {
    expect(bundler).toContain('writeDeployAppYaml');
    expect(bundler).toMatch(/from:\s*path\.join\(root, 'app\.yaml'\)/);
  });

  it('has no literal env block of its own', () => {
    const withoutComments = bundler.replace(/\/\*[\s\S]*?\*\//g, '').replace(/\/\/[^\n]*/g, '');

    expect(
      withoutComments,
      'bundle-server.mjs is writing app.yaml env from a literal again. That is a second source ' +
        'of truth, and it drops whatever app.yaml adds.'
    ).not.toMatch(/env:\s*\\n\s*-\s*name:|`command:[\s\S]*?\nenv:/);
  });

  it('reads the build stamp before it rewrites the tracked output tree', () => {
    // build/deploy is tracked, so `git status` sees this build's own output.
    // Resolving the stamp after the rewrite stamped every build +dirty, including
    // one from a pristine checkout, and no committed bundle could ever carry a
    // clean stamp: committing it produced a commit whose app.yaml differed again.
    const withoutComments = bundler.replace(/\/\*[\s\S]*?\*\//g, '').replace(/\/\/[^\n]*/g, '');
    const resolved = withoutComments.indexOf('resolveBuildStamp()');
    const destroyed = withoutComments.search(/rm\(outDir/);

    expect(resolved, 'bundle-server.mjs no longer resolves a build stamp').toBeGreaterThan(-1);
    expect(destroyed, 'bundle-server.mjs no longer clears outDir').toBeGreaterThan(-1);
    expect(
      resolved,
      'the build stamp is resolved after build/deploy is rewritten, so the build measures its ' +
        'own output as source dirt and stamps +dirty from a clean checkout.'
    ).toBeLessThan(destroyed);
  });

  it('refuses to publish an app artifact with an empty build stamp', () => {
    expect(bundler).toContain('No app build stamp could be resolved');
    expect(bundler).toContain('PLAYER_INSIGHTS_SOURCE_SHA');
  });
});
