#!/usr/bin/env python3
"""Emit AnswerContract bindings from the Python model.

PIA-P1-4. `contracts.AnswerContract` is the schema. This writes the JSON Schema
and the TypeScript / Python field lists so the app cannot drift from the agent
without a failed test.

    python generate_answer_contract.py
"""

from __future__ import annotations

import json
from pathlib import Path

from contracts import AnswerContract

ROOT = Path(__file__).resolve().parent


def shared_generated() -> Path:
    for repo in [ROOT.parent, *ROOT.parent.parents]:
        candidates = (
            repo / "player-insights-agent" / "shared" / "generated",
            repo / "app" / "shared" / "generated",
            repo / "platform" / "app" / "shared" / "generated",
        )
        for path in candidates:
            shared = path.parent
            if any(
                (shared / marker).is_file()
                for marker in (
                    "core-response-contract.ts",
                    "failure-taxonomy.ts",
                    "app-schema.ts",
                )
            ):
                path.mkdir(parents=True, exist_ok=True)
                return path
    raise SystemExit("could not find an app shared/ directory next to this agent")


SCHEMA_PATH = ROOT / "schemas" / "answer-contract.json"
PY_PATH = ROOT / "generated_answer_contract.py"


def field_names(model: type) -> list[str]:
    return list(model.model_fields)


def render_python(names: list[str]) -> str:
    listed = ",\n    ".join(repr(name) for name in names)
    return (
        '"""Wire field names for AnswerContract.\n\n'
        "Generated by generate_answer_contract.py. Do not edit.\n"
        '"""\n\n'
        "from __future__ import annotations\n\n"
        f"ANSWER_CONTRACT_FIELDS: tuple[str, ...] = (\n    {listed},\n)\n"
    )


def render_typescript(names: list[str]) -> str:
    listed = ",\n  ".join(json.dumps(name) for name in names)
    return (
        "/** Wire field names for AnswerContract.\n"
        " * Generated by agent/generate_answer_contract.py. Do not edit.\n"
        " */\n"
        f"export const ANSWER_CONTRACT_FIELDS = [\n  {listed},\n] as const;\n\n"
        "export type AnswerContractField = (typeof ANSWER_CONTRACT_FIELDS)[number];\n"
    )


def main() -> int:
    names = field_names(AnswerContract)
    schema = AnswerContract.model_json_schema()
    ts_path = shared_generated() / "answer-contract.ts"
    SCHEMA_PATH.parent.mkdir(parents=True, exist_ok=True)
    SCHEMA_PATH.write_text(json.dumps(schema, indent=2) + "\n", encoding="utf-8")
    PY_PATH.write_text(render_python(names), encoding="utf-8")
    ts_path.write_text(render_typescript(names), encoding="utf-8")
    print(f"wrote {SCHEMA_PATH}")
    print(f"wrote {PY_PATH}")
    print(f"wrote {ts_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
